FROM microsoft/vsts-agent:$(VSTS_AGENT_TAG)

ENV DOCKER_BUCKET get.docker.com
ENV DOCKER_VERSION $(DOCKER_VERSION)
ENV DOCKER_SHA256 $(DOCKER_SHA256)

RUN set -x \
 && curl -fSL "https://${DOCKER_BUCKET}/builds/`uname -s`/`uname -m`/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
 && echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
 && tar -xzvf docker.tgz \
 && mv docker/* /usr/local/bin/ \
 && rmdir docker \
 && rm docker.tgz \
 && docker -v

ENV DOCKER_COMPOSE_VERSION $(DOCKER_COMPOSE_VERSION)

RUN set -x \
 && curl -fSL "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m`" -o /usr/local/bin/docker-compose \
 && chmod +x /usr/local/bin/docker-compose \
 && docker-compose -v

COPY ./docker-start.sh .
RUN chown vsts:vsts docker-start.sh

CMD ["./docker-start.sh"]
