#!/bin/bash
set -e

PROCESS=$1

while read UBUNTU_VERSION LIBICU_VERSION; do
  $PROCESS $UBUNTU_VERSION $LIBICU_VERSION
  derived/docker/$PROCESS.sh ubuntu-$UBUNTU_VERSION "$(pwd)/$UBUNTU_VERSION"
  while read VSTS_AGENT_VERSION VSTS_AGENT_RELEASE; do
    VSTS_AGENT_RELEASE=${VSTS_AGENT_RELEASE:-$VSTS_AGENT_VERSION}
    $PROCESS $UBUNTU_VERSION $LIBICU_VERSION $VSTS_AGENT_VERSION $VSTS_AGENT_RELEASE
    derived/docker/$PROCESS.sh ubuntu-$UBUNTU_VERSION-$VSTS_AGENT_RELEASE "$(pwd)/$UBUNTU_VERSION/$VSTS_AGENT_RELEASE" $VSTS_AGENT_VERSION $VSTS_AGENT_RELEASE
  done < <(cat versioned/versions | grep -v ^# | sed 's/\r//')
done < <(cat versions | sed 's/\r//')
