FROM ubuntu:$(UBUNTU_VERSION)

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        software-properties-common \
 && apt-add-repository ppa:git-core/ppa \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
        curl \
        git \
        libcurl3 \
        libicu$(LIBICU_VERSION) \
        libunwind8 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /vsts

RUN set -x \
 && curl -fSL https://github.com/Microsoft/vsts-agent/releases/download/v$(VSTS_AGENT_VERSION)/vsts-agent-ubuntu.$(UBUNTU_VERSION)-x64-$(VSTS_AGENT_VERSION).tar.gz -o agent.tgz \
 && mkdir agent \
 && cd agent \
 && tar -xzf ../agent.tgz \
 && chown -R root:root . \
 && cd .. \
 && rm agent.tgz

COPY ./start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
