FROM ubuntu:$(UBUNTU_VERSION)

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        software-properties-common \
 && apt-add-repository ppa:git-core/ppa \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
        curl \
        git \
        libcurl3 \
        libicu$(LIBICU_VERSION) \
        libunwind8 \
 && rm -rf /var/lib/apt/lists/*

RUN adduser --system --group vsts
WORKDIR /home/vsts/agent

RUN set -x \
 && curl -fSL https://github.com/Microsoft/vsts-agent/releases/download/v$(VSTS_AGENT_VERSION)/vsts-agent-ubuntu.$(UBUNTU_VERSION)-x64-$(VSTS_AGENT_VERSION).tar.gz -o agent.tgz \
 && tar -xzf agent.tgz \
 && chown -R vsts:vsts . \
 && rm agent.tgz

COPY ./start.sh .
RUN chown vsts:vsts start.sh \
 && chmod +x start.sh

CMD ["./start.sh"]
