FROM microsoft/vsts-agent:$(VSTS_AGENT_TAG)

# Install packages
RUN echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet-release/ $(UBUNTU_RELEASE) main" > /etc/apt/sources.list.d/dotnetdev.list \
 && apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
    # Essential build tools (gcc, make, etc.)
    build-essential \
    # Basic utilities
    curl \
    dnsutils \
    ftp \
    iproute2 \
    iputils-ping \
    openssh-client \
    sudo \
    telnet \
    time \
    unzip \
    wget \
    zip \
    # Python
    python \
    python3 \
    # Java and related build tools
    openjdk-$(OPENJDK_VERSION)-jdk \
    ant \
    gradle \
    maven \
    # .NET Core SDK
    dotnet-dev-1.0.0-preview2-003131 \
 && rm -rf /var/lib/apt/lists/*

# Install stable Node.js and related build tools
RUN curl -sL https://git.io/n-install | bash -s -- -ny - \
 && ~/n/bin/n stable \
 && npm install -g bower grunt gulp n \
 && rm -rf ~/n

# Configure environment variables
RUN export M2_HOME=$(which mvn) \
 && export ANT_HOME=$(which ant) \
 && export dotnet=$(which dotnet) \
 && export GRADLE_HOME=$(which gradle)
