# escape=`
FROM microsoft/vsts-agent:windows-core-ltsc2019

LABEL name="microsoft/vsts-agent:windows-core-ltsc2019-2.141.1" `
      version="0.0.1"

# Download Agent
ADD https://vstsagentpackage.azureedge.net/agent/2.141.1/vsts-agent-win-x64-2.141.1.zip C:\TFS\agent.zip

WORKDIR C:\TFS

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Expand-Archive agent.zip -DestinationPath .\Agent -Force; `
    Remove-Item -Force agent.zip

SHELL ["cmd", "/S", "/C"]

ENV chocolateyUseWindowsCompression=false

RUN @powershell -ExecutionPolicy Bypass -Command "iex (Invoke-WebRequest 'https://chocolatey.org/install.ps1' -UseBasicParsing)" `
 && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

RUN choco config set cachelocation C:\chococache

COPY ./Run-Agent.ps1 .
COPY ./Cleanup-Agent.ps1 .

ENTRYPOINT ["powershell.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
CMD ["try {C:/TFS/Run-Agent.ps1;}finally {C:/TFS/Cleanup-Agent.ps1;}"]

